name: Code Coverage

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Setup Node.js v16
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x

            - name: Install Dependencies
              run: yarn install

            - name: Test Coverage
              run: yarn test:coverage

            - name: Push to Codecov
              uses: codecov/codecov-action@v2
              with:
                  directory: ./coverage
                  token: ${{ secrets.CODECOV_TOKEN }}
